#!/bin/bash

op=$(echo $1 | cut -d ' ' -f 2)
number1=$(echo $1 | cut -d ' ' -f 1)
number2=$(echo $1 | cut -d ' ' -f 3)
total=$((number1 $op number2))

# display the result
echo "The result of the do-op is $total"