#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No arguments"
    exit 1
else
    for i in $*; do
        if ! [[ $i =~ ^[0-9]+$ ]]; then
            echo "Not a number"
            exit 1
        fi
    done
fi